import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='nav'>
          <Link href={"/"} className='todaytodo'>Today</Link>
          <Link href={"/month"} className='month'>Month</Link>
          <Link href={"/bucketbox"} className='bucketbox'>BucketBox</Link>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
